name: 'Terraform Setup'
description: 'Initializes Terraform with backend config and selects workspace'
inputs:
  terraform_dir:
    description: 'Path to Terraform directory'
    required: false
    default: 'infrastructure-web-app/terraform'
  state_bucket:
    description: 'S3 bucket for Terraform state'
    required: true
  state_key:
    description: 'S3 key for Terraform state'
    required: true
  state_region:
    description: 'AWS region for Terraform state'
    required: true
  workspace:
    description: 'Terraform workspace to select'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.5
        terraform_wrapper: false

    - name: Initialize Terraform
      shell: bash
      working-directory: ${{ inputs.terraform_dir }}
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.state_bucket }}" \
          -backend-config="key=${{ inputs.state_key }}" \
          -backend-config="region=${{ inputs.state_region }}" \
          -input=false

    - name: Select workspace
      shell: bash
      working-directory: ${{ inputs.terraform_dir }}
      run: |
        terraform workspace select ${{ inputs.workspace }} 2>/dev/null || \
        terraform workspace new ${{ inputs.workspace }} || {
          echo "❌ Failed to select or create workspace: ${{ inputs.workspace }}"
          exit 1
        }
        echo "✅ Using workspace: $(terraform workspace show)"

